USE master
GO
 DROP DATABASE ToDoListProject
 go
CREATE DATABASE ToDoListProject
GO

USE ToDoListProject
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Status](
	[StatusId] [INT] NOT NULL IDENTITY(1,1),
	[Name] NVARCHAR(15) NOT NULL,
	CONSTRAINT [PK_Status] PRIMARY KEY CLUSTERED 
	([StatusId] ASC	)
	WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY] )
	ON [PRIMARY]
	GO
    

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ToDo](
	[Id] [INT] IDENTITY(1,1) NOT NULL,
	[Name] NVARCHAR(max) NOT NULL,
	[StatusId] [INT] NOT NULL FOREIGN KEY REFERENCES Status(StatusId),
	[Description] NVARCHAR(max) null,
	[Deadline] DATETIME NOT NULL,
	CONSTRAINT [PK_Todo] PRIMARY KEY CLUSTERED
	([Id] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
	) ON [PRIMARY] TEXTIMAGE_ON [Primary]
GO

